[package]
name = "bdserver"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
futures-util = "0.3.31"
serde = "1.0.214"
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["full"] }
mongodb = "3.1.0"
async-trait = "0.1.83"
chrono = "0.4.38"
bincode = "1.3.3"

